# Generated by Django 5.1.1 on 2024-10-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=255)),
                ('price_band', models.CharField(max_length=100)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('ipo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_gain', models.CharField(max_length=100)),
                ('new_listing_date', models.DateField(blank=True, null=True)),
                ('current_market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_return', models.CharField(max_length=100)),
                ('rhp_pdf', models.FileField(upload_to='rhp_pdfs/')),
                ('drhp_pdf', models.FileField(upload_to='drhp_pdfs/')),
            ],
        ),
    ]
